### ISSUE TITLE
Spinners do not Fetch Current State if Changed Externally

### ISSUE THREAD

**Issue by chrisramsay** [JonnyHonda/TimeTracker-Binary#2]
If the state of a currently running timer is changed externally from the application - i.e. in Kimai, the spinners do not update to reflect the new state.

Steps to reproduce:

- Set a timer running in app
- Go into Kimai and edit currently running entry: change project or activity
- In app, refresh the view
- Note that Text at page top has changed but spinners still reflect old state

**Comment by JonnyHonda** [comment]
Fixed in v1.7
